#!/bin/bash
# [settings.conf] - Глобальные настройки системы
# Переменная со значением по умолчанию VAR_NAME="${VAR_NAME:-var_name_default}"

# --- ПАРАМЕТРЫ ПРОЕКТА ---
export PROJECT_NAME="${PROJECT_NAME:=default}"
export AUTHOR="${AUTHOR:="DevOps Admin"}"
export VERSION="${VERSION:=2.1.0}"
# Папка задается в ядре core.sh
# export readonly ROOT_DIR=""

# --- ЛОГИРОВАНИЕ (logger.sh) ---
LOG_TO_CONSOLE=true
LOG_TO_FILE=true
LOG_FILE="${ROOT_DIR}/var/log/${PROJECT_NAME}.log"
DEBUG_MODE=true  # Включите для подробного вывода при отладке

# --- БЭКАПЫ (backup.sh) ---
BACKUP_ENABLE=true
BACKUP_DIST="${BACKUP_DIST:=${ROOT_DIR}/var/backups}"
BACKUP_COMPRESSION="tar -I 'zstd -T0'"
BACKUP_EXT="tar.zst"
BACKUP_KEEP_DAYS=14
# Папка по умолчанию (mktemp -d) /tmp/{уникальное имя папки}
# BACKUP_TEMP=""

# --- ПУТИ ТРАНЗАКЦИЙ (transaction.sh) ---
#TRANSACTION_ACTIVE=false
TRANSACTION_LOG="${ROOT_DIR}/var/log/transaction.log"
STAGING_DIR="${ROOT_DIR}/var/tmp/staging"
BACKUP_DIR="${ROOT_DIR}/var/tmp/backup"

# --- МЕНЕДЖЕР ПАКЕТОВ (installer.sh) ---
PKG_MANAGER="apt-get"
PKG_OPTS="-y -qq"

log_debug "Конфигурация [settings.conf] успешно загружена."